services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - sifa-network  # ← Usar red externa

networks:
  sifa-network:
    external: true  # ← Indicar que es externa
